//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_finalDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbFinalEntities : DbContext
    {
        public dbFinalEntities()
            : base("name=dbFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TableAccommodation2034> TableAccommodation2034 { get; set; }
        public virtual DbSet<TableBrowser2034> TableBrowser2034 { get; set; }
        public virtual DbSet<TableSight2034> TableSight2034 { get; set; }
    }
}
