//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_finalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableBrowser2034
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableBrowser2034()
        {
            this.TableSight2034 = new HashSet<TableSight2034>();
            this.TableAccommodation2034 = new HashSet<TableAccommodation2034>();
        }
    
        public string bNo { get; set; }
        public string bName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string bPhone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableSight2034> TableSight2034 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableAccommodation2034> TableAccommodation2034 { get; set; }
    }
}
